services:
  wishlist:
    extends:
      file: docker-compose-base.yaml
      service: wishlist
    build:
      context: .
      dockerfile: devcontainer-dockerfile
    ports:
      - 8080:8080
  wishlist-db:
    extends:
      file: docker-compose-base.yaml
      service: wishlist-db
  wishlist-mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - wishlist-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
  wishlist-dapr:
    extends:
      file: docker-compose-base.yaml
      service: wishlist-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
volumes:
  wishlist-db-data:
