services:
  app:
    build:
      context: .
      dockerfile: dev-dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: mongo
  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017
