services:
  wishlist:
    restart: unless-stopped
    build:
      context: .
      dockerfile: base-dockerfile
    healthcheck:
      test: wget http://localhost:8080/graphiql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      wishlist-db:
        condition: service_healthy
  wishlist-db:
    image: mongo
    volumes:
      - wishlist-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  wishlist-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "wishlist",
        "--app-port",
        "8080",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path", "/components"
      ]
    network_mode: "service:wishlist"
volumes:
  wishlist-db-data:
